# Generated by Django 6.0.6 on 2026-07-15 03:26

from django.db import migrations

def update_resin_data(apps, schema_editor):
    Resin = apps.get_model('main', 'tbl_resin')

    # 1. Update PE to HDPE
    # We use .filter().update() because it doesn't crash if 'PE' was already changed or doesn't exist
    Resin.objects.filter(abbreviation='PE').update(abbreviation='HDPE')

    # 2. Add LDPE with code 'E'
    # get_or_create prevents duplicate errors if you run this twice
    Resin.objects.get_or_create(abbreviation='LDPE', code='E')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20260711_1049'),
    ]

    operations = [
        migrations.RunPython(update_resin_data),
    ]
