# Generated by Django 6.0.6 on 2026-07-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tbl_cmf_color_req_cm'),
    ]

    operations = [
    ]
