# Generated by Django 6.0.6 on 2026-07-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20260710_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
