# Generated by Django 6.0.6 on 2026-07-10 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20260710_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_coding_materials',
            fields=[
                ('lab_material_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=1)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_coding_materials',
            },
        ),
        migrations.CreateModel(
            name='tbl_resins',
            fields=[
                ('resin_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=None, max_length=22, null=True)),
                ('abbreviation', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=3)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_resins',
            },
        ),
        migrations.RemoveField(
            model_name='tbl_cmf_formula',
            name='resin',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='resin',
        ),
        migrations.AddField(
            model_name='tbl_cmf_formula',
            name='resin_no',
            field=models.ForeignKey(blank=True, db_column='resin_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_resins'),
        ),
        migrations.AddField(
            model_name='tbl_rs',
            name='resin_no',
            field=models.ForeignKey(blank=True, db_column='resin_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_resins'),
        ),
    ]
