# Generated by Django 6.0.6 on 2026-07-16 06:04

from django.db import migrations

def populate_cmf_references(apps, schema_editor):
    # Fetch Models
    Specification = apps.get_model('main', 'tbl_cmf_specification')
    Process = apps.get_model('main', 'tbl_cmf_process')
    Salesman = apps.get_model('main', 'tbl_cmf_salesman')

    # 1. Update Specifications
    specs = ["Food Contact", "Sunlight Exposure"]
    for s_name in specs:
        Specification.objects.get_or_create(name=s_name)

    # 2. Update Processes
    processes = ["Injection", "Blow-Molding", "Film", "Pipe Extrusion"]
    for p_name in processes:
        Process.objects.get_or_create(name=p_name)

    # 3. Update Salesmen
    salesmen = [
        "Joseph Garcia",
        "Mary Jane Doria",
        "Babylyn Jintalan",
        "Rolando Hernandez",
        "Mary Jean De Lumpa",
        "Ian Villegas"
    ]
    for s_name in salesmen:
        Salesman.objects.get_or_create(name=s_name)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20260715_1126'),
    ]

    operations = [
        migrations.RunPython(populate_cmf_references),
    ]
