# Generated by Django 6.0.6 on 2026-07-17 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20260716_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_cmf_color_req',
            old_name='cm',
            new_name='cm_no',
        ),
        migrations.RenameField(
            model_name='tbl_cmf_dates',
            old_name='cm',
            new_name='cm_no',
        ),
        migrations.RenameField(
            model_name='tbl_cmf_formula',
            old_name='cm',
            new_name='cm_no',
        ),
        migrations.RenameField(
            model_name='tbl_cmf_process02',
            old_name='cmf_formula',
            new_name='cmf_formula_no',
        ),
        migrations.RenameField(
            model_name='tbl_cmf_process02',
            old_name='process',
            new_name='process_no',
        ),
        migrations.RenameField(
            model_name='tbl_cmf_specification02',
            old_name='cm',
            new_name='cm_no',
        ),
        migrations.RenameField(
            model_name='tbl_dc_extruder_formula',
            old_name='cm',
            new_name='cm_no',
        ),
        migrations.RenameField(
            model_name='tbl_mb_extruder_formula',
            old_name='cm',
            new_name='cm_no',
        ),
        migrations.RenameField(
            model_name='tbl_resins_selected',
            old_name='cm',
            new_name='cm_no',
        ),
        migrations.RenameField(
            model_name='tbl_resins_selected',
            old_name='resin',
            new_name='resin_no',
        ),
        migrations.RenameField(
            model_name='tbl_rs',
            old_name='cm',
            new_name='cm_no',
        ),
        migrations.RemoveField(
            model_name='tbl_cmf_pending_completed',
            name='matching_type',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback_details',
            name='cm_rs_no',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback_details',
            name='rm_feedback_no',
        ),
        migrations.AddField(
            model_name='tbl_cmf_pending_completed',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_rs', to_field='rs_no'),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='A',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='B',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='C',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='H',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='L',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='html',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='k',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='ar_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='cm_no',
            field=models.ForeignKey(db_column='cm_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf', to_field='cm_no'),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='code_submitted',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='date_sample_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='lot_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='pieces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='quantity_given',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='rs_no',
            field=models.ForeignKey(db_column='rs_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs', to_field='rs_no'),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='A',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='B',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='C',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='H',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='L',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='html',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='k',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='m',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_cmf_pending_completed',
            name='cm_no',
            field=models.ForeignKey(blank=True, db_column='cm_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf', to_field='cm_no'),
        ),
        migrations.AlterField(
            model_name='tbl_feedback_details',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
