# Generated by Django 6.0.6 on 2026-07-18 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_cm_tbl_cmf_color_req_cm_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cmf',
            name='primary_color',
        ),
        migrations.AddField(
            model_name='tbl_cmf',
            name='in_code_no',
            field=models.ForeignKey(blank=True, db_column='in_code_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_internal_color_code'),
        ),
    ]
