# Generated by Django 6.0.6 on 2026-07-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_tbl_cmf_primary_color_tbl_cmf_in_code_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_cmf_specification02',
            old_name='spec',
            new_name='spec_no',
        ),
    ]
