# Generated by Django 6.0.6 on 2026-07-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_spec_tbl_cmf_specification02_spec_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mb_extruder_formula',
            name='lot_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
