# Generated by Django 6.0.6 on 2026-07-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tbl_mb_extruder_formula_lot_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback_details',
            name='ar_no',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback_details',
            name='lot_no',
        ),
        migrations.AddField(
            model_name='tbl_cmf_pending_completed',
            name='lot_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
