# Generated by Django 6.0.6 on 2026-07-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_tbl_feedback_details_ar_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rs',
            name='quantity_required',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
