# Generated by Django 6.0.6 on 2026-07-25 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tbl_rs_quantity_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cmf_color_req',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs', to_field='rs_no'),
        ),
        migrations.AddField(
            model_name='tbl_cmf_process02',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs', to_field='rs_no'),
        ),
        migrations.AddField(
            model_name='tbl_resins_selected',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs', to_field='rs_no'),
        ),
        migrations.AddField(
            model_name='tbl_rs',
            name='code_no',
            field=models.ForeignKey(blank=True, db_column='code_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_generated_prod_code'),
        ),
        migrations.AddField(
            model_name='tbl_rs',
            name='sm_no',
            field=models.ForeignKey(blank=True, db_column='sm_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_cmf_salesman'),
        ),
        migrations.AlterField(
            model_name='tbl_cmf_process02',
            name='cmf_formula_no',
            field=models.ForeignKey(blank=True, db_column='cmf_formula_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf_formula'),
        ),
        migrations.AlterField(
            model_name='tbl_resins_selected',
            name='cm_no',
            field=models.ForeignKey(blank=True, db_column='cm_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf', to_field='cm_no'),
        ),
    ]
