# Generated by Django 6.0.6 on 2026-07-25 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_tbl_cmf_color_req_rs_no_tbl_cmf_process02_rs_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_rs',
            name='ar_no',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='code_no',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='color_description',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='date_sample_received',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='lot_no',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='quantity_given',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='status',
        ),
    ]
