# Generated by Django 6.0.6 on 2026-07-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_tbl_rs_ar_no_remove_tbl_rs_code_no_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE tbl_cmf_pending_completed DROP CONSTRAINT tbl_cmf_pending_completed_rs_no_af8a940b_fk_tbl_rs_rs_no;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE tbl_feedback_details DROP CONSTRAINT tbl_feedback_details_rs_no_51c4be21_fk_tbl_rs_rs_no;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE tbl_cmf_color_req DROP CONSTRAINT tbl_cmf_color_req_rs_no_da6e433e_fk_tbl_rs_rs_no;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE tbl_cmf_process02 DROP CONSTRAINT tbl_cmf_process02_rs_no_b370f9ac_fk_tbl_rs_rs_no;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE tbl_resins_selected DROP CONSTRAINT tbl_resins_selected_rs_no_da5ab006_fk_tbl_rs_rs_no;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE tbl_rs_prod_codes DROP CONSTRAINT tbl_rs_prod_codes_rs_no_b6d31567_fk_tbl_rs_rs_no;',
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
