# Generated by Django 6.0.6 on 2026-07-25 07:14

from django.db import migrations

TABLES = [
    'tbl_cmf_pending_completed',
    'tbl_feedback_details',
    'tbl_cmf_color_req',
    'tbl_cmf_process02',
    'tbl_resins_selected',
    'tbl_rs_prod_codes',
]


def populate(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, rs_no FROM tbl_rs WHERE rs_no IS NOT NULL")
        rs_lookup = {rs_no: rs_id for rs_id, rs_no in cursor.fetchall()}

        for table in TABLES:
            cursor.execute(f"SELECT ctid, rs_no FROM {table} WHERE rs_no IS NOT NULL")
            rows = cursor.fetchall()
            for ctid, old_val in rows:
                new_id = rs_lookup.get(old_val)
                if new_id is None:
                    cursor.execute(f"UPDATE {table} SET rs_no = NULL WHERE ctid = %s", [ctid])
                else:
                    cursor.execute(f"UPDATE {table} SET rs_no = %s WHERE ctid = %s", [str(new_id), ctid])


def reverse_noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_drop_old_rs_fk_constraints'),
    ]

    operations = [
        migrations.RunPython(populate, reverse_noop),
    ]
