# Generated by Django 6.0.6 on 2026-07-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_populate_rs_id_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cmf_color_req',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs'),
        ),
        migrations.AlterField(
            model_name='tbl_cmf_pending_completed',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_rs'),
        ),
        migrations.AlterField(
            model_name='tbl_cmf_process02',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs'),
        ),
        migrations.AlterField(
            model_name='tbl_feedback_details',
            name='rs_no',
            field=models.ForeignKey(db_column='rs_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs'),
        ),
        migrations.AlterField(
            model_name='tbl_resins_selected',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs'),
        ),
        migrations.AlterField(
            model_name='tbl_rs',
            name='rs_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_rs_prod_codes',
            name='rs',
            field=models.ForeignKey(blank=True, db_column='rs_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_rs'),
        ),
    ]
