# Generated by Django 6.0.6 on 2026-07-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_tbl_cmf_color_req_rs_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rs',
            name='dosage',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
