# Generated by Django 6.0.6 on 2026-07-28 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tbl_rs_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_rs'),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_rs'),
        ),
    ]
