# Generated by Django 6.0.6 on 2026-07-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_tbl_dc_extruder_formula_rs_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
