# Generated by Django 6.0.6 on 2026-07-30 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_tbl_dc_extruder_formula_is_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cmf_pending_completed',
            name='code',
            field=models.ForeignKey(blank=True, db_column='code_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_generated_prod_code'),
        ),
    ]
