# Generated by Django 6.0.6 on 2026-07-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_tbl_cmf_pending_completed_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cmf_pending_completed',
            name='prod_code',
        ),
    ]
