# Generated by Django 6.0.6 on 2026-07-30 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_tbl_cmf_pending_completed_prod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cmf_dates',
            name='rs_no',
            field=models.ForeignKey(blank=True, db_column='rs_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_rs'),
        ),
        migrations.AlterField(
            model_name='tbl_cmf_dates',
            name='cm_no',
            field=models.ForeignKey(blank=True, db_column='cm_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.tbl_cmf', to_field='cm_no'),
        ),
    ]
