# Generated by Django 6.0.6 on 2026-07-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_tbl_cmf_dates_rs_no_alter_tbl_cmf_dates_cm_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_rs',
            name='date_form_made',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='date_lab_received',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='date_required',
        ),
        migrations.RemoveField(
            model_name='tbl_rs',
            name='due_date',
        ),
    ]
