# Generated by Django 6.0.6 on 2026-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_tbl_rs_date_form_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
