# Generated by Django 6.0.6 on 2026-08-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_tbl_mb_extruder_formula_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='application',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='cm_no',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='customer',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='date_time',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='index_no',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='mix_time',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='prod_color',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='product_code',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula',
            name='resin',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula_encode',
            name='encoded_by',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula_encode',
            name='match_by',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula_encode',
            name='updated_by',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_master_formula_info',
            name='material_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
