# Generated by Django 6.0.6 on 2026-08-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_tbl_master_formula_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='in_mb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='in_mb',
            field=models.BooleanField(default=False),
        ),
    ]
