# Generated by Django 6.0.6 on 2026-08-07 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_tbl_dc_extruder_formula_in_mb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_dc_extruder_formula',
            old_name='in_mb',
            new_name='in_master_formula',
        ),
        migrations.RenameField(
            model_name='tbl_mb_extruder_formula',
            old_name='in_mb',
            new_name='in_master_formula',
        ),
    ]
