# Generated by Django 6.0.6 on 2026-08-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_in_mb_tbl_dc_extruder_formula_in_master_formula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_master_formula',
            old_name='date_time',
            new_name='date_modified',
        ),
    ]
