# Generated by Django 6.0.6 on 2026-08-11 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_date_time_tbl_master_formula_date_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_feedback_details',
            name='code_submitted',
        ),
        migrations.AddField(
            model_name='tbl_feedback_details',
            name='code',
            field=models.ForeignKey(blank=True, db_column='code_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_generated_prod_code'),
        ),
    ]
