# Generated by Django 6.0.6 on 2026-08-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_tbl_mb_extruder_formula02_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_dc_extruder_formula02',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True),
        ),
    ]
