# Generated by Django 6.0.6 on 2026-08-17 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_tbl_dc_extruder_formula02_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dc_extruder_materials',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(blank=True, max_length=150, null=True)),
                ('dc', models.ForeignKey(db_column='dc_no', on_delete=django.db.models.deletion.CASCADE, related_name='dc_materials', to='main.tbl_dc_extruder_formula')),
            ],
            options={
                'db_table': 'tbl_dc_extruder_materials',
            },
        ),
        migrations.CreateModel(
            name='tbl_dc_extruder_version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_no', models.IntegerField()),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('material', models.ForeignKey(db_column='material_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.tbl_dc_extruder_materials')),
            ],
            options={
                'db_table': 'tbl_dc_extruder_version',
            },
        ),
        migrations.DeleteModel(
            name='tbl_dc_extruder_formula02',
        ),
    ]
