# Generated by Django 6.0.6 on 2026-08-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_tbl_dc_extruder_materials_tbl_dc_extruder_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tbl_customer',
            },
        ),
    ]
