# Generated by Django 6.0.6 on 2026-08-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_tbl_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cmf',
            name='est_qty_order',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated quantity in KG', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='tbl_cmf',
            name='product_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('existing', 'Existing')], default='new', max_length=10, null=True),
        ),
    ]
