# Generated by Django 6.0.6 on 2026-08-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_tbl_cmf_est_qty_order_tbl_cmf_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cmf_scanned',
            name='file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
