# Generated by Django 6.0.6 on 2026-08-25 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_tbl_cmf_scanned_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='material_code',
            field=models.ForeignKey(blank=True, db_column='lab_material_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tbl_coding_materials'),
        ),
    ]
