# Generated by Django 6.0.6 on 2026-08-26 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_tbl_dc_extruder_formula_material_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_dc_extruder_formula',
            name='matcher',
            field=models.ForeignKey(blank=True, db_column='matcher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tbl_mb_extruder_formula',
            name='matcher',
            field=models.ForeignKey(blank=True, db_column='matcher_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
