# Generated by Django 6.0.6 on 2026-08-26 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_tbl_dc_extruder_formula_matcher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_dc_extruder_formula',
            old_name='matcher',
            new_name='matcher_id',
        ),
        migrations.RenameField(
            model_name='tbl_mb_extruder_formula',
            old_name='matcher',
            new_name='matcher_id',
        ),
    ]
