# Generated by Django 6.0.6 on 2026-08-26 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_matcher_tbl_dc_extruder_formula_matcher_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_dc_extruder_formula',
            old_name='matcher_id',
            new_name='matcher',
        ),
        migrations.RenameField(
            model_name='tbl_mb_extruder_formula',
            old_name='matcher_id',
            new_name='matcher',
        ),
    ]
