# Generated by Django 6.0.6 on 2026-08-29 08:09

import django.db.models.deletion
from django.db import migrations, models

def add_options(apps, schema_editor):
    Option = apps.get_model('main', 'tbl_submitted_option')
    for name in ['Sample', 'Chips', 'Price']:
        Option.objects.get_or_create(name=name)

def remove_options(apps, schema_editor):
    Option = apps.get_model('main', 'tbl_submitted_option')
    Option.objects.filter(name__in=['Sample', 'Chips', 'Price']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_matcher_id_tbl_dc_extruder_formula_matcher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_submitted_option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_submitted_option',
            },
        ),
        migrations.RenameField(
            model_name='tbl_cmf_pending_completed',
            old_name='id',
            new_name='completed_id',
        ),
        migrations.CreateModel(
            name='tbl_submitted_selected',
            fields=[
                ('submitted_id', models.AutoField(primary_key=True, serialize=False)),
                ('completed_id', models.ForeignKey(db_column='completed_id', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_selections', to='main.tbl_cmf_pending_completed')),
                ('option_id', models.ForeignKey(db_column='option_id', on_delete=django.db.models.deletion.CASCADE, to='main.tbl_submitted_option')),
            ],
            options={
                'db_table': 'tbl_submitted_selected',
                'unique_together': {('completed_id', 'option_id')},
            },
        ),
        migrations.DeleteModel(
            name='tbl_rs_prod_codes',
        ),
        migrations.RunPython(add_options, remove_options),
    ]
