# Generated by Django 6.0.6 on 2026-09-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_tbl_submitted_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_master_formula',
            name='colorant_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
